const customHydCities = [
  "Most Searched",
  "Hitech City",
  "Madhapur",
  "Durgam Cheruvu",
  "Rai Durg",
  "Banjara Hills",
  "Jubilee Hills",
  "Gachibowli",
  "Kondapur",
  "Secunderabad",
  "Kukatpally",
];
const vikarabadLocalities = [
  "Shivaram Nagar Colony",
  "Kanyalaalbagh Colony",
  "Vidhyanagar",
  "Alampally",
  "B.T.S Colony",
  "New Gunj",
  "APHB Colony",
  "Ananthagiri Road Area",
  "Railway Station Area",
  "Vikar Manzil Area",
  "Sultan Manzil Area",
  "Gangaram",
  "Teachers Colony",
  "P&T Colony",
  "Ashok Nagar",
];
const vizagLocalities = [
  "Most Searched",
  "MVP Colony",
  "Seethammadhara",
  "Madhurawada",
  "Lawsons Bay Colony",
  "Waltair Uplands",
  "Gajuwaka",
  "Dwaraka Nagar",
  "Rushikonda",
  "Asilmetta",
];
const bengaluruLocalities = [
  "Most Searched",
  "Indiranagar",
  "Koramangala",
  "Whitefield",
  "Jayanagar",
  "Malleshwaram",
  "Electronic City",
  "HSR Layout",
  "Marathahalli",
  "Banashankari",
  "MG Road",
];
const chennaiLocalities = [
  "Most Searched",
  "Anna Nagar",
  "T. Nagar",
  "Adyar",
  "Velachery",
  "Mylapore",
  "Besant Nagar",
  "Nungambakkam",
  "Tambaram",
  "OMR (Old Mahabalipuram Road)",
  "Egmore",
];
const mumbaiLocalities = [
  "Most Searched",
  "Bandra",
  "South Mumbai (Colaba)",
  "Andheri",
  "Powai",
  "Juhu",
  "Worli",
  "Malad",
  "Dadar",
  "Khar",
  "Borivali",
];
const puneLocalities = [
  "Most Searched",
  "Koregaon Park",
  "Kothrud",
  "Hinjewadi",
  "Viman Nagar",
  "Baner",
  "Aundh",
  "Hadapsar",
  "Wakad",
  "Magarpatta",
  "Shivaji Nagar",
];
export {
  customHydCities,
  vizagLocalities,
  bengaluruLocalities,
  chennaiLocalities,
  mumbaiLocalities,
  puneLocalities,
  vikarabadLocalities,
};
